language: python
os:
    - linux
python:
    - '3.7'
    - '3.8'
    - '3.9'
    - '3.10'
    - nightly
    - pypy
cache: python
install: pip install tox
script: tox -e py
notifications:
    email:
        on_success: never
matrix:
    fast_finish: true
    allow_failures:
        - python: nightly
        - python: pypy
